#ifndef WIFI_PORTAL_PAGE_H
#define WIFI_PORTAL_PAGE_H

static const char WIFI_PORTAL_HTML[] =
"<!doctype html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"  <title>eDog 配网</title>\n"
"  <style>\n"
"    :root {\n"
"      --bg: #efe9de;\n"
"      --panel: rgba(255,255,255,0.92);\n"
"      --ink: #1f2b2e;\n"
"      --muted: #5d6b70;\n"
"      --accent: #0f766e;\n"
"      --accent-strong: #115e59;\n"
"      --warn: #b45309;\n"
"      --ok: #166534;\n"
"      --shadow: 0 24px 60px rgba(26, 39, 45, 0.12);\n"
"    }\n"
"    * { box-sizing: border-box; }\n"
"    body {\n"
"      margin: 0;\n"
"      min-height: 100vh;\n"
"      display: flex;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"      padding: 20px;\n"
"      background:\n"
"        radial-gradient(circle at top left, rgba(15,118,110,0.16), transparent 36%),\n"
"        radial-gradient(circle at bottom right, rgba(180,83,9,0.15), transparent 30%),\n"
"        linear-gradient(145deg, #f7f2e9, var(--bg));\n"
"      color: var(--ink);\n"
"      font-family: \"Avenir Next\", \"Trebuchet MS\", sans-serif;\n"
"    }\n"
"    main {\n"
"      width: min(100%, 420px);\n"
"      background: var(--panel);\n"
"      border: 1px solid rgba(31, 43, 46, 0.08);\n"
"      border-radius: 24px;\n"
"      box-shadow: var(--shadow);\n"
"      padding: 28px 24px 24px;\n"
"      backdrop-filter: blur(10px);\n"
"    }\n"
"    .eyebrow {\n"
"      display: inline-block;\n"
"      padding: 6px 10px;\n"
"      border-radius: 999px;\n"
"      background: rgba(15, 118, 110, 0.1);\n"
"      color: var(--accent-strong);\n"
"      font-size: 12px;\n"
"      font-weight: 700;\n"
"      letter-spacing: 0.08em;\n"
"      text-transform: uppercase;\n"
"    }\n"
"    h1 {\n"
"      margin: 18px 0 10px;\n"
"      font-size: 30px;\n"
"      line-height: 1.05;\n"
"    }\n"
"    p {\n"
"      margin: 0;\n"
"      color: var(--muted);\n"
"      line-height: 1.6;\n"
"    }\n"
"    form {\n"
"      margin-top: 22px;\n"
"    }\n"
"    label {\n"
"      display: block;\n"
"      margin-top: 14px;\n"
"      font-size: 14px;\n"
"      color: var(--ink);\n"
"      font-weight: 600;\n"
"    }\n"
"    input {\n"
"      width: 100%;\n"
"      margin-top: 8px;\n"
"      padding: 14px 16px;\n"
"      border-radius: 16px;\n"
"      border: 1px solid rgba(31, 43, 46, 0.15);\n"
"      background: rgba(255,255,255,0.92);\n"
"      color: var(--ink);\n"
"      font-size: 16px;\n"
"      outline: none;\n"
"    }\n"
"    input:focus {\n"
"      border-color: rgba(15, 118, 110, 0.45);\n"
"      box-shadow: 0 0 0 4px rgba(15, 118, 110, 0.12);\n"
"    }\n"
"    button {\n"
"      width: 100%;\n"
"      margin-top: 18px;\n"
"      padding: 14px 16px;\n"
"      border: 0;\n"
"      border-radius: 16px;\n"
"      background: linear-gradient(135deg, var(--accent), #0b5f71);\n"
"      color: #fff;\n"
"      font-size: 16px;\n"
"      font-weight: 700;\n"
"      cursor: pointer;\n"
"    }\n"
"    button:disabled {\n"
"      opacity: 0.65;\n"
"      cursor: wait;\n"
"    }\n"
"    .status {\n"
"      margin-top: 16px;\n"
"      padding: 12px 14px;\n"
"      border-radius: 14px;\n"
"      background: rgba(15, 118, 110, 0.08);\n"
"      color: var(--accent-strong);\n"
"      min-height: 48px;\n"
"    }\n"
"    .status.warn {\n"
"      background: rgba(180, 83, 9, 0.12);\n"
"      color: var(--warn);\n"
"    }\n"
"    .status.ok {\n"
"      background: rgba(22, 101, 52, 0.12);\n"
"      color: var(--ok);\n"
"    }\n"
"    .tips {\n"
"      margin-top: 18px;\n"
"      font-size: 13px;\n"
"      line-height: 1.7;\n"
"      color: var(--muted);\n"
"    }\n"
"    strong {\n"
"      color: var(--ink);\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <main>\n"
"    <div class=\"eyebrow\">eDog 配网</div>\n"
"    <h1>连接家庭 Wi-Fi</h1>\n"
"    <p>请输入 eDog 需要连接的 Wi-Fi 名称和密码，保存后设备会自动尝试联网。</p>\n"
"    <form id=\"wifi-form\">\n"
"      <label for=\"ssid\">Wi-Fi 名称\n"
"        <input id=\"ssid\" name=\"ssid\" maxlength=\"63\" autocomplete=\"off\" required>\n"
"      </label>\n"
"      <label for=\"password\">Wi-Fi 密码\n"
"        <input id=\"password\" name=\"password\" type=\"password\" maxlength=\"63\" autocomplete=\"current-password\">\n"
"      </label>\n"
"      <button id=\"submit\" type=\"submit\">保存并连接</button>\n"
"    </form>\n"
"    <div id=\"status\" class=\"status\">等待输入 Wi-Fi 信息。</div>\n"
"    <div class=\"tips\">\n"
"      <div>如果页面没有自动打开，请手动访问 <strong id=\"gateway\">设备地址</strong>。</div>\n"
"      <div>已保存的网络会存储在设备中，下次开机会自动重连。</div>\n"
"    </div>\n"
"  </main>\n"
"  <script>\n"
"    (function () {\n"
"      var form = document.getElementById('wifi-form');\n"
"      var statusNode = document.getElementById('status');\n"
"      var submitButton = document.getElementById('submit');\n"
"      var gatewayNode = document.getElementById('gateway');\n"
"      gatewayNode.textContent = window.location.origin || window.location.host || '设备地址';\n"
"\n"
"      function setStatus(message, kind) {\n"
"        statusNode.className = 'status' + (kind ? ' ' + kind : '');\n"
"        statusNode.textContent = message;\n"
"      }\n"
"\n"
"      form.addEventListener('submit', function (event) {\n"
"        var ssid = document.getElementById('ssid').value.replace(/^\\s+|\\s+$/g, '');\n"
"        var password = document.getElementById('password').value.replace(/^\\s+|\\s+$/g, '');\n"
"        var xhr;\n"
"        var payload;\n"
"\n"
"        event.preventDefault();\n"
"\n"
"        if (!ssid) {\n"
"          setStatus('请填写 Wi-Fi 名称。', 'warn');\n"
"          return;\n"
"        }\n"
"\n"
"        submitButton.disabled = true;\n"
"        setStatus('正在保存网络信息，eDog 即将切换到联网模式...', '');\n"
"\n"
"        xhr = new XMLHttpRequest();\n"
"        xhr.open('POST', '/api/wifi/config', true);\n"
"        xhr.setRequestHeader('Content-Type', 'application/json');\n"
"        xhr.onreadystatechange = function () {\n"
"          var response;\n"
"          if (xhr.readyState !== 4) {\n"
"            return;\n"
"          }\n"
"          submitButton.disabled = false;\n"
"          if (xhr.status === 0) {\n"
"            setStatus('设备热点已断开，eDog 可能正在切换到家庭 Wi-Fi，请稍候观察设备是否已联网。', 'ok');\n"
"            return;\n"
"          }\n"
"          try {\n"
"            response = JSON.parse(xhr.responseText || '{}');\n"
"          } catch (error) {\n"
"            response = {};\n"
"          }\n"
"          if (xhr.status >= 200 && xhr.status < 300) {\n"
"            setStatus(response.message || 'Wi-Fi 信息已保存，eDog 正在连接网络。', 'ok');\n"
"          } else {\n"
"            setStatus(response.message || '保存 Wi-Fi 信息失败，请重试。', 'warn');\n"
"          }\n"
"        };\n"
"        payload = JSON.stringify({ ssid: ssid, password: password });\n"
"        xhr.send(payload);\n"
"      });\n"
"    })();\n"
"  </script>\n"
"</body>\n"
"</html>\n";

#endif
